workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.0
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
      - name: Build Android App Bundle (Debug)
        script: |
          flutter build appbundle --debug --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
